
version: "3" 
# volumes of drivers 

volumes:
  db:
    driver: local
    # name: db
    driver_opts:
      o: bind
      device: /Users/yismaili/Desktop/Inception/srcs/data/mariadb
  wp:
    driver: local
    # name: wp
    driver_opts:
      o: bind
      device: /Users/yismaili/Desktop/Inception/srcs/data/wordpress
# networks of drivers
networks:
  appnwrk:
    # name: appnwrk
    driver: bridge
# run containers 
services: 
  mariadb:
      container_name: mariadb
      env_file:
        - .env
      ports:
        - 3360:3360
      build: ./requirements/mariadb
      restart: on-failure
      volumes:
        - db:/var/lib/mysql
      networks:
        - appnwrk
  wordpress:
      container_name: wordpress
      env_file:
        - .env
      depends_on:
        - mariadb
      build: ./requirements/wordpress
      restart: on-failure
      ports:
        - 9000:9000
      volumes:
        - wp:/var/www/html
      networks:
        - appnwrk
  nginx:
      container_name: nginx
      build: ./requirements/nginx
      depends_on:
        - wordpress
      restart: on-failure
      ports: 
       - 443:443
      volumes:
        - wp:/var/www/html
      networks:
        - appnwrk
  adminer:
    container_name: adminer
    build: ./bonus/Adminer
    depends_on:
        - wordpress
    restart: on-failure
    ports:
      - "8282:8282"
    networks:
      - appnwrk
  wibsete:
    container_name: wibset
    build: ./bonus/website
    ports:
      - 80:80
    networks:
      - appnwrk
  redis:
    container_name: redis
    build: ./bonus/redis
    depends_on:
        - wordpress
    ports: 
       - 6379:6379
    networks:
      - appnwrk
  ftp:
    container_name: ftp
    build: ./bonus/ftp_server
    depends_on:
        - wordpress
    ports:
      - "40000-40006:40000-40006"
      - "21:21"
      - "20:20"
    networks:
      - appnwrk
    env_file:
      - .env
    volumes:
      - wp:/home/yismail/ftp
    restart: on-failure
  cadvisor:
    container_name: cadvisor
    build: ./bonus/cAdvisor
    volumes:
      - /:/rootfs:ro # access and collect resource usage data from the host's filesystem
      - /var/run:/var/run:rw #allows CAdvisor to access and collect resource usage data from the host's running processes.
      - /sys:/sys:ro #allows CAdvisor to access and collect resource usage data from the host's system information
      - /var/lib/docker/:/var/lib/docker:ro # allows CAdvisor to access and collect resource usage data from the host's running Docker containers
    ports:
      - "8080:8080"
    networks:
      - appnwrk
    restart: on-failure