
version: "3" 
# volumes of drivers 

volumes:
  db:
    driver: local
    # name: db
    driver_opts:
      type: none
      o: bind
      device: /Users/yismaili/Desktop/Inception/srcs/data/mariadb
  wp:
    driver: local
    # name: wp
    driver_opts:
      type: none
      o: bind
      device: /Users/yismaili/Desktop/Inception/srcs/data/wordpress
# networks of drivers

networks:
  appnwrk:
    # name: appnwrk
    driver: bridge
# run containers 
services: 
  mariadb:
      container_name: mariadb
      env_file:
        - .env
      build: ./requirements/mariadb
      restart: always
      volumes:
        - db:/var/lib/mysql
      networks:
        - appnwrk
  wordpress:
      container_name: wordpress
      env_file:
        - .env
      depends_on:
        - mariadb
      build: ./requirements/wordpress
      restart: always
      ports:
        - 9000:9000
      volumes:
        - wp:/var/www/html
      networks:
        - appnwrk
  nginx:
      container_name: nginx
      build: ./requirements/nginx
      depends_on:
        - wordpress
      restart: always
      ports: 
       - 443:443
      volumes:
        - wp:/var/www/html
      networks:
        - appnwrk
  adminer:
    build: ./bonus/Adminer
    restart: always
    ports:
      - "8282:8282"
    networks:
      - appnwrk
  wibsete:
    build: ./bonus/website
    ports:
      - 80:80
    networks:
      - appnwrk
  redis:
    build: ./bonus/redis
    ports: 
       - 6379:6379
    networks:
      - appnwrk