
version: "3" 
# volumes of drivers 

volumes:
  mr_db:
    driver: local
    # name: mr_db
    driver_opts:
      type: none
      o: bind
      device: ./mariadb
  wrdprs:
    driver: local
    # name: wrdprs
    driver_opts:
      type: none
      o: bind
      device: ./wordpress
# networks of drivers

networks:
  appnwrk:
    # name: appnwrk
    driver: bridge
      # driver_opts:
      #   type: none
# run containers 
services: 
  mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      restart: always
      volumes:
        - mr_db:/var/lib/mysql
      networks:
        - appnwrk
  wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      restart: always
      volumes:
        - wrdprs:/var/www/html
      networks:
        - appnwrk
  nginx:
      container_name: nginx
      build: ./requirements/nginx
      depends_on:
        - wordpress
      restart: always
      volumes:
        - wrdprs:/var/www/html
      networks:
        - appnwrk
    